name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/master
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Canary-API-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    agent_pool: 'AWS-ECS'
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_producer_approval: true
    python_version: ${{ variables.python_version }}
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
      - environment: internal-dev-sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
      - environment: internal-qa
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
      - environment: internal-qa-sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
      - environment: ref
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
        depends_on:
          - internal_qa
      - environment: dev
        service_name: "${{ variables.service_name }}-dep"
        short_service_name: "${{ variables.short_service_name }}-dep"
        service_base_path: "${{ variables.service_base_path }}-dep"
        spec_file: ${{ variables.spec_file }}
        python_version: ${{ variables.python_version }}
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              test_type: smoketest
              app_id: "7af455b3-e2b8-4c73-bb20-3d044cd2cc25"
        depends_on:
          - internal_qa
      - environment: int
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              app_id: "f636ac69-6906-4b30-96cf-a21b316a207e"
              test_type: smoketest
        depends_on:
          - internal_qa
      - environment: sandbox
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              app_id: "44900ab5-7b6c-4dbe-8d1b-0ed4850b0e76"
              test_type: smoketest
        depends_on:
          - internal_qa
      - environment: prod
        post_deploy:
          - template: templates/e2e.yml
            parameters:
              app_id: "0fb7e1b5-14cc-48cf-993e-06b27d7cb2da"
              test_type: smoketest
        depends_on:
          - int
