name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/master
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Canary-API-Build"
    trigger:
      branches:
        exclude:
          - main
          - refs/heads/main
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    deploy_review_sandbox: false
    post_deploy:
      - template: templates/e2e.yml
        parameters:
          test_type: smoketest
    apigee_deployments:
      - environment: internal-dev
      - environment: internal-dev
        stage_name: internal-dev-blue
        service_name: canary-api-blue
        service_base_path: canary-api-blue
      - environment: internal-dev
        stage_name: internal-dev-green
        service_name: canary-api-green
        service_base_path: canary-api-green
      - environment: internal-dev-sandbox
      - environment: int
      - environment: int
        stage_name: int_no_smartcard
        fully_qualified_service_name: identity-service-int-no-smartcard
        service_base_path: oauth2-no-smartcard
        jinja_templates:
          IDENTITY_TARGET_SERVER: identity-server-no-smartcard
          VARIABLES_KVM: identity-service-variables-no-smartcard
          ENCRYPTED_VARIABLES_KVM: identity-service-variables-encrypted-no-smartcard
          NUM_RANDOM_LONG_INTS_FOR_STATE: 4
