name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/pull/331/merge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Canary-API-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    post_deploy:
      - template: templates/e2e.yml
        parameters:
          test_type: smoketest
    apigee_deployments:
      - environment: internal-dev
      - environment: internal-dev-sandbox
      - environment: internal-qa
      - environment: internal-qa-sandbox
      - environment: sandbox
      - environment: dev
      - environment: int
      - environment: ref
      - environment: prod
