name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/apm-1746-integrate-s3-cache-into-utils
      endpoint: NHSDigital

variables:
  - template: project.yml
extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    global_install: false
    pre_install_steps:
      - task: s3-cache-action@1
        inputs:
          key: 'node modules | ${{ parameters.service_name }} | package-lock.json'
          location: 'node_modules'
          debug: true
          alias: 'NodeModules'
        displayName: cache node modules
      - bash: |
          # source ~/.nvm/nvm.sh
          make install-node
        condition: ne(variables['CacheRestored-NodeModules'], 'true')
        workingDirectory: '${{ parameters.service_name }}'
        displayName: Install node dependencies
      - task: s3-cache-action@1
        inputs:
          key: 'poeetry | ${{ parameters.service_name }} | poetry.lock'
          location: '.venv'
          debug: true
          alias: 'Poetry'
        displayName: cache node modules
      - bash: |
          make install-python
        condition: ne(variables['CacheRestored-Poetry'], 'true')
        workingDirectory: '${{ parameters.service_name }}'
        displayName: Install python dependencies
      - bash: make install-hooks
        workingDirectory: '${{ parameters.service_name }}'
        displayName: Install hooks
