name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/master
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Canary-API-Build"
    trigger:
      branches:
        exclude:
          - main
          - refs/heads/main
          - refs/tags/v*

# Test change. remove when finished

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

stages:
  - stage: Custom approval
    displayName: Manual Approval
    dependsOn: []
    jobs:
      - deployment: build # Or deploy?
        displayName: Manual Approval Required
        timeoutInMinutes: 40
        pool:
          name: Ubuntu-16.04
        environment: "infrastructure-approval-ptl"
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - bash: |
                      echo Approved

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    deploy_review_sandbox: false
    post_deploy:
      - template: templates/e2e.yml
        parameters:
          test_type: smoketest
