name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: simulate_deploy
    jobs:
    - job: use_s3_cache_action
      steps:
        - task: s3-cache-action@0.0.2
          inputs:
            samplestring: 'Test File'
