name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: simulate-deploy
    jobs:
    - job: Use S3 Cache Action
      steps:
        - task: s3-cache-action@0
          inputs:
            samplestring: 'Test File'
