name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: s3-cache-action
      type: github
      name: NHSDigital/apim-s3-cache-action
      ref: refs/heads/apm-1741-pipelines-integration-poc
      endpoint: NHSDigital

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: simulate_deploy
    jobs:
    - job: checkout_repos
      steps:
        - checkout: self

        - checkout: s3-cache-action

    - job: display_repos
      steps:
        - bash: |
            echo Route
            ls
