name: PR Quality Check
on: pull_request
jobs:
  link-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: NHSDigital/ticket-check-action@master
        id: ticket-check

      - name: Comment on PR with link to JIRA ticket
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            This branch is work on a ticket in the NHS Digital AMB JIRA Project. Here's a handy link to the ticket:
            # [${{ steps.ticket-check.ticket-id }}](https://nhsd-jira.digital.nhs.uk/browse/${{ steps.ticket-check.ticket-id }})
      
      - name: Comment on PR with link to Spec
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            This branch is working on a ticket to deploy to internal-portal. Here's a handy link to the specification:
            # [${{ github.event.pull_request.head.ref }} specification](https://internal-portal.developer.nhs.uk/docs/hello-world-pr-${{ github.event.number }}/1/overview)
